import type { FieldDef } from './components/admin/CrudSection'
import type { SectionKey } from './types'

export type SectionNav = { key: SectionKey; label: string }

export const SECTION_NAV: SectionNav[] = [
  { key: 'profile', label: 'Profile' },
  { key: 'experience', label: 'Experience' },
  { key: 'education', label: 'Education' },
  { key: 'certifications', label: 'Licenses & Certifications' },
  { key: 'projects', label: 'Projects' },
  { key: 'blog_posts', label: 'Blog' },
  { key: 'volunteer', label: 'Volunteer' },
  { key: 'skills', label: 'Skills' },
  { key: 'languages', label: 'Languages' },
  { key: 'honors', label: 'Honors & Awards' },
  { key: 'publications', label: 'Publications' },
  { key: 'courses', label: 'Courses' },
  { key: 'recommendations', label: 'Recommendations' },
]

export const CRUD_SECTIONS: Record<
  Exclude<SectionKey, 'profile'>,
  { apiPath: string; title: string; fields: FieldDef[]; emptyItem: () => Record<string, unknown>; labelKey: string }
> = {
  experience: {
    apiPath: 'experience',
    title: 'Experience',
    labelKey: 'title',
    emptyItem: () => ({
      company: '',
      title: '',
      location: '',
      start_date: '',
      end_date: null,
      description: '',
      order: 0,
    }),
    fields: [
      { key: 'title', label: 'Job title', required: true },
      { key: 'company', label: 'Company', required: true },
      { key: 'location', label: 'Location' },
      { key: 'start_date', label: 'Start date', placeholder: 'Jan 2020' },
      { key: 'end_date', label: 'End date (blank = Present)', placeholder: 'Dec 2023' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  education: {
    apiPath: 'education',
    title: 'Education',
    labelKey: 'school',
    emptyItem: () => ({
      school: '',
      degree: '',
      field: '',
      start_date: '',
      end_date: null,
      description: '',
      order: 0,
    }),
    fields: [
      { key: 'school', label: 'School', required: true },
      { key: 'degree', label: 'Degree' },
      { key: 'field', label: 'Field of study' },
      { key: 'start_date', label: 'Start date' },
      { key: 'end_date', label: 'End date' },
      { key: 'description', label: 'Activities & description', type: 'textarea' },
    ],
  },
  certifications: {
    apiPath: 'certifications',
    title: 'Licenses & Certifications',
    labelKey: 'title',
    emptyItem: () => ({
      title: '',
      issuer: '',
      issue_date: '',
      expiry_date: null,
      credential_id: '',
      credential_url: '',
      order: 0,
    }),
    fields: [
      { key: 'title', label: 'Name', required: true },
      { key: 'issuer', label: 'Issuing organization' },
      { key: 'issue_date', label: 'Issue date' },
      { key: 'expiry_date', label: 'Expiration date' },
      { key: 'credential_id', label: 'Credential ID' },
      { key: 'credential_url', label: 'Credential URL' },
    ],
  },
  projects: {
    apiPath: 'projects',
    title: 'Projects',
    labelKey: 'title',
    emptyItem: () => ({
      title: '',
      description: '',
      url: '',
      image_url: '',
      tags: [],
      featured: false,
      order: 0,
    }),
    fields: [
      { key: 'title', label: 'Project name', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'url', label: 'Project URL' },
      { key: 'image_url', label: 'Image URL' },
      { key: 'tags', label: 'Tags', type: 'tags' },
      { key: 'featured', label: 'Featured on profile', type: 'checkbox' },
    ],
  },
  blog_posts: {
    apiPath: 'blog-posts',
    title: 'Blog posts',
    labelKey: 'title',
    emptyItem: () => ({
      title: '',
      excerpt: '',
      body: '',
      cover_image_url: '',
      tags: [],
      published_date: '',
      published: false,
      order: 0,
    }),
    fields: [
      { key: 'title', label: 'Title', required: true },
      { key: 'excerpt', label: 'Excerpt', type: 'textarea', placeholder: 'Short summary for the blog list (optional)' },
      { key: 'body', label: 'Post body', type: 'textarea', required: true },
      { key: 'cover_image_url', label: 'Cover image URL' },
      { key: 'tags', label: 'Tags', type: 'tags' },
      { key: 'published_date', label: 'Published date', placeholder: 'Jun 2026' },
      { key: 'published', label: 'Published (visible on site)', type: 'checkbox' },
    ],
  },
  volunteer: {
    apiPath: 'volunteer',
    title: 'Volunteer Experience',
    labelKey: 'organization',
    emptyItem: () => ({
      organization: '',
      role: '',
      cause: '',
      start_date: '',
      end_date: null,
      description: '',
      order: 0,
    }),
    fields: [
      { key: 'organization', label: 'Organization', required: true },
      { key: 'role', label: 'Role' },
      { key: 'cause', label: 'Cause' },
      { key: 'start_date', label: 'Start date' },
      { key: 'end_date', label: 'End date' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  skills: {
    apiPath: 'skills',
    title: 'Skills',
    labelKey: 'name',
    emptyItem: () => ({ name: '', order: 0 }),
    fields: [{ key: 'name', label: 'Skill name', required: true }],
  },
  languages: {
    apiPath: 'languages',
    title: 'Languages',
    labelKey: 'name',
    emptyItem: () => ({ name: '', proficiency: '', order: 0 }),
    fields: [
      { key: 'name', label: 'Language', required: true },
      { key: 'proficiency', label: 'Proficiency', placeholder: 'Native, Professional, Limited…' },
    ],
  },
  honors: {
    apiPath: 'honors',
    title: 'Honors & Awards',
    labelKey: 'title',
    emptyItem: () => ({
      title: '',
      issuer: '',
      issue_date: '',
      description: '',
      order: 0,
    }),
    fields: [
      { key: 'title', label: 'Title', required: true },
      { key: 'issuer', label: 'Issuer' },
      { key: 'issue_date', label: 'Date' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  publications: {
    apiPath: 'publications',
    title: 'Publications',
    labelKey: 'title',
    emptyItem: () => ({
      title: '',
      publisher: '',
      publication_date: '',
      url: '',
      description: '',
      order: 0,
    }),
    fields: [
      { key: 'title', label: 'Title', required: true },
      { key: 'publisher', label: 'Publisher' },
      { key: 'publication_date', label: 'Publication date' },
      { key: 'url', label: 'URL' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  courses: {
    apiPath: 'courses',
    title: 'Courses',
    labelKey: 'name',
    emptyItem: () => ({
      name: '',
      number: '',
      associated_with: '',
      order: 0,
    }),
    fields: [
      { key: 'name', label: 'Course name', required: true },
      { key: 'number', label: 'Course number' },
      { key: 'associated_with', label: 'Associated with (school/org)' },
    ],
  },
  recommendations: {
    apiPath: 'recommendations',
    title: 'Recommendations',
    labelKey: 'recommender_name',
    emptyItem: () => ({
      recommender_name: '',
      recommender_title: '',
      relationship: '',
      text: '',
      date: '',
      order: 0,
    }),
    fields: [
      { key: 'recommender_name', label: 'Recommender name', required: true },
      { key: 'recommender_title', label: 'Recommender title' },
      { key: 'relationship', label: 'Relationship', placeholder: 'Managed John directly' },
      { key: 'date', label: 'Date' },
      { key: 'text', label: 'Recommendation text', type: 'textarea' },
    ],
  },
}
